### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by herobrine30396** [NXPHoverGames/RapidIoT#2]
There are 14 errors while building:

![Screenshot from 2019-11-11 20-55-45](https://user-images.githubusercontent.com/51438133/68598931-b2059480-04c5-11ea-9d0a-b1dcf9e920c5.png)
And it's path:
![Screenshot from 2019-11-11 20-55-53](https://user-images.githubusercontent.com/51438133/68599034-dbbebb80-04c5-11ea-8add-9f1262fea6d5.png)

**Comment by KatrinMoritz** [comment]
Did you follow the instructions under the heading "Include the Mavlink Demo into the “Hello World” example"? It seems like the UART and the GPIO Pins for USER_SW are not routed on your board. Its important to be in the right functional group in the peripherals menu. The UART has to be configured in the "BOARD_Init_TERMIANL_UART" and the USER_SW in the inital group.

**Comment by herobrine30396** [comment]
Yes, I followed those instructions.
![image](https://user-images.githubusercontent.com/51438133/68671750-0b2d0100-0576-11ea-9e0b-6abf04760628.png)
![image](https://user-images.githubusercontent.com/51438133/68671769-1718c300-0576-11ea-8aff-9f67fc437c07.png)
Not sure how to configure "USER_SW in the inital group"

**Comment by KatrinMoritz** [comment]
Please see the corrected Readme with additional information on how to set up the project. 
The bugs are unfortunately not fixed by the new Project config. A new "pin_mux.h" file is created by activating UART2 and the macros in the project are no longer consistent. I described how to fix this here:  https://nxp.gitbook.io/hovergames/addons/rapid-iot/mavlink-for-rapid-iot
please try this.

**Comment by Niel66** [comment]
I still have a few errors:

![image](https://user-images.githubusercontent.com/51438133/69876628-1443ff00-12e6-11ea-84fa-8fd64af27500.png)
